### PR TITLE
Any time a lists item qty is changed it sends a signal

### PR DESCRIPTION
**Pull request by Roger-Chavez**
Closes #(issue)

### Key features
* Anytime a user changes the qty of a list a signal is emitted
* Allows us to display total qty of items within the list and update changes as they happen 

### Future Improvements
* none
### Notes
none

### CODE REVIEW

**Review by ChrisRzech — COMMENTED** [review]
The signal should give some information about what item has been changed

**Review by ChrisRzech — APPROVED** [review]
👍

**Review by WakkaTrout — APPROVED** [review]
Nothing changed too much other than the addition of the signal, so since it was approved before, I approve it now

**Review by yosmo78 — APPROVED** [review]
looks good

**Pull request merged**
